// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPIglo_t49wP1dqWh5dmxPuuzPLThlE-E',
    appId: '1:294287952972:web:09a8f9ba824e6884cd78e9',
    messagingSenderId: '294287952972',
    projectId: 'pruebas-8ea96',
    authDomain: 'pruebas-8ea96.firebaseapp.com',
    storageBucket: 'pruebas-8ea96.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa-6c5X36OHSlZqSRjv5zVmJ4rLh1j4ds',
    appId: '1:294287952972:android:6ca30a78b25a4386cd78e9',
    messagingSenderId: '294287952972',
    projectId: 'pruebas-8ea96',
    storageBucket: 'pruebas-8ea96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5hnKcGJ_4XiCzOlm1mvR8hFSURz-EnlE',
    appId: '1:294287952972:ios:4b09fd4331b46ccccd78e9',
    messagingSenderId: '294287952972',
    projectId: 'pruebas-8ea96',
    storageBucket: 'pruebas-8ea96.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5hnKcGJ_4XiCzOlm1mvR8hFSURz-EnlE',
    appId: '1:294287952972:ios:4b09fd4331b46ccccd78e9',
    messagingSenderId: '294287952972',
    projectId: 'pruebas-8ea96',
    storageBucket: 'pruebas-8ea96.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPIglo_t49wP1dqWh5dmxPuuzPLThlE-E',
    appId: '1:294287952972:web:7b55312d8ad8c337cd78e9',
    messagingSenderId: '294287952972',
    projectId: 'pruebas-8ea96',
    authDomain: 'pruebas-8ea96.firebaseapp.com',
    storageBucket: 'pruebas-8ea96.firebasestorage.app',
  );
}
